Laboratory Task 5

In [16]:
#1. Perform Standard Imports
import torch
import numpy as np
import sys
import random

In [17]:
#2. Create a function called set_seed() that accepts seed: int as a parameter, this function must return nothing but just set the seed to a certain value
def set_seed(seed: int):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)

In [18]:
#3. Create a NumPy array called "arr" that contains 6 random integers between 0 (inclusive) and 5 (exclusive), call the set_seed() function and use 42 as the seed parameter.
set_seed(42)
arr = np.random.randint(0, 5, size=6)
print("NumPy array arr:", arr)

NumPy array arr: [3 4 2 4 4 1]


In [19]:
# 4. Create a tensor "x" from the array above
x = torch.from_numpy(arr)
print("\nTensor x:", x)


Tensor x: tensor([3, 4, 2, 4, 4, 1], dtype=torch.int32)


In [20]:
#5. Change the dtype of x from int32 to int64
x = x.to(torch.int64)
print("\nTensor x with dtype int64:", x, x.dtype)


Tensor x with dtype int64: tensor([3, 4, 2, 4, 4, 1]) torch.int64


In [21]:
#6. Reshape x into a 3x2 tensor,There are several ways to do this
x = x.view(3, 2)
print ("\nRight-hand column:\n", x)


Right-hand column:
 tensor([[3, 4],
        [2, 4],
        [4, 1]])


In [22]:
#7. Return the right-hand column of tensor x
right_col = x[:,1]
print("\nRight-hand column:\n", right_col)


Right-hand column:
 tensor([4, 4, 1])


In [23]:
#8. Without changing x, return a tensor of square values of x, There are several ways to do this.
x_squared = x **2
print("\nSquared values of x:\n", x_squared)


Squared values of x:
 tensor([[ 9, 16],
        [ 4, 16],
        [16,  1]])


In [24]:
# 9. Create a tensor y with the same number of elements as x, that can be matrix-multiplied with x, Use PyTorch directly (not NumPy) to create a tensor of random integers between 0 (inclusive) and 5 (exclusive). Use 42 as seed. Think about what shape it should have to permit matrix multiplication.
set_seed(42)
y = torch.randint(0,5,(2,3), dtype=torch.int64)
print("\nTensor y (2x3):\n", y)


Tensor y (2x3):
 tensor([[2, 2, 1],
        [4, 1, 0]])


In [25]:
#10. Find the matrix product of x and y.
matmul_result = torch.matmul(x,y)
print("\nMatrix product x @ y:\n", matmul_result)


Matrix product x @ y:
 tensor([[22, 10,  3],
        [20,  8,  2],
        [12,  9,  4]])
